### PR TITLE
rename kuutamo to kneard-deploy

### PR DESCRIPTION
**Pull request by Mic92**
update bors.toml

### CODE REVIEW

**Comment by Mic92** [comment]
bors cancel

**Comment by Mic92** [comment]
bors try

**Review by yanganto — APPROVED** [review]

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Comment by yanganto** [comment]
fix dep conflict

**Comment by yanganto** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Pull request merged**
